plugins { id 'com.android.application' }

android {
    namespace 'com.ofirgilboa.kolyaakov'
    compileSdk 36

    defaultConfig {
        applicationId 'com.ofirgilboa.kolyaakov'
        minSdk 26
        targetSdk 36
        versionCode 401
        versionName '0.4.1'
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
        }
    }
}
